### PR TITLE
Support ocamlformat

### PR DESCRIPTION
**Pull request by wpcarro**
- Runs `ocamlformat` across project's source code
- Adds job to .circleci/config.yml to assert that the project is formatted

### CODE REVIEW

**Comment by wpcarro** [comment]
As I'm pretty new to the OCaml community, I'm unsure if the style that the `.ocamlformat` config is giving us is desirable or not. If there are some options that we'd like to set and others that we'd like to unset, let me know and I can make those changes.

Otherwise, unless I'm mistaken, this should be good to go.

**Comment by wpcarro** [comment]
@pbiggar should be all set to go!

**Comment by pbiggar** [comment]
I don't see the settings in the PR? As a reminder:

> Can you use these settings?

```
profile = sparse
break-string-literals = never
escape-strings = preserve
```

**Comment by wpcarro** [comment]
@pbiggar I believe you added `.ocamlformat` with those exact settings. See [here](https://github.com/darklang/tablecloth/blob/master/.ocamlformat). Unless I'm misunderstanding your ask, we should be ok. No?

**Comment by wpcarro** [comment]
Let me know if there's anything else you'd like me to change before we can submit this. Thanks!

**Comment by pbiggar** [comment]
Thank you!

**Pull request merged**
