### PR TITLE
change Array.empty to be a function

### LINKED ISSUE #100: bucklescript 7.0.2-dev.2 builds are broken
https://github.com/BuckleScript/bucklescript/issues/4087
After this change empty array has concrete type, current interface is expecting it to be polymorphic

### PR DESCRIPTION
**Pull request by Coobaha**
This fixes #100 but introduces a breaking change

Should native api also be changed?

### CODE REVIEW

**Comment by pbiggar** [comment]
That's a nice fix, thanks! Yes, native API should also be changed. Also see formatting errors.

Thanks, would be delighted to merge once native API is changed and CI passes :)

**Comment by Coobaha** [comment]
@pbiggar done! <3

**Comment by Coobaha** [comment]
@pbiggar ping!

**Comment by tienle** [comment]
Any update on this? @Coobaha  @pbiggar .

**Comment by pbiggar** [comment]
Thanks for the fix, and apologies for the long delay!

**Pull request merged**
