### PR TITLE
Add paket

### PR DESCRIPTION
**Pull request by OceanOak**

### CODE REVIEW

**Review by pbiggar — CHANGES_REQUESTED** [review]
I would expect to add this in the fsharp directory?

**Comment by OceanOak** [comment]
Even if I move it to the fsharp directory running "dotnet build" generates a new one in tablecloth directory.
Any idea why this is happening?

**Comment by pbiggar** [comment]
Which directory are you running dotnet build from?

**Comment by OceanOak** [comment]
> Which directory are you running dotnet build from?

fsharp/src

**Comment by pbiggar** [comment]
Weird. I'd expect to call dotnet build from the fsharp directory though.

**Comment by OceanOak** [comment]
Running dotnet build from the fsharp directory raise this error
MSBuild version 17.3.1+2badb37d1 for .NET
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

**Comment by pbiggar** [comment]
I moved F# code to https://github.com/darklang/tablecloth-rescript so closing for now

**Pull request closed without merging**
