### PR TITLE
Add andThen2 with Interface, Documentation and Tests

### PR DESCRIPTION
**Pull request by shubhamkumar13**
adding andThen2 as a response to issue #160

### CODE REVIEW

**Comment by shubhamkumar13** [comment]
Forgot to add tests.
Going to check the doc generation failures.

**Comment by shubhamkumar13** [comment]
The tests that are failing are a result of me not having a proper way of formatting re/ml files.

Any suggestion regarding this would be very helpful, I created a fresh switch for tablecloth with the following packages (as a result of `make-deps`)
```
# Packages matching: installed
# Name                  # Installed # Synopsis
alcotest                1.2.3       Alcotest is a lightweight and colourful test framework
astring                 0.8.5       Alternative String module for OCaml
base                    v0.14.0     Full standard library replacement for OCaml
base-bigarray           base
base-threads            base
base-unix               base
cmdliner                1.0.4       Declarative definition of command line interfaces for OCaml
conf-m4                 1           Virtual package relying on m4
cppo                    1.6.6       Code preprocessor like cpp for OCaml
csexp                   1.3.2       Parsing and printing of S-expressions in Canonical form
dune                    2.7.1       Fast, portable, and opinionated build system
dune-configurator       2.7.1       Helper library for gathering system configuration
fix                     20200131    Facilities for memoization and fixed points
fmt                     0.8.8       OCaml Format pretty-printer combinators
fpath                   0.7.3       File system paths for OCaml
junit                   2.0.2       JUnit XML reports generation library
junit_alcotest          2.0.2       JUnit XML reports generation for alcotest tests
menhir                  20200624    An LR(1) parser generator
menhirLib               20200624    Runtime support library for parsers generated by Menhir
menhirSdk               20200624    Compile-time library for auxiliary tools related to Menhir
merlin-extend           0.6         A protocol to provide custom frontend to Merlin
ocaml                   4.10.0      The OCaml compiler (virtual package)
ocaml-config            1           OCaml Switch Configuration
ocaml-migrate-parsetree 1.7.3       Convert OCaml parsetrees between different versions
ocaml-system            4.10.0      The OCaml compiler (system version, from outside of opam)
ocamlbuild              0.14.0      OCamlbuild is a build system with builtin rules to easily b
ocamlfind               1.8.1       A library manager for OCaml
odoc                    1.5.1       OCaml documentation generator
ppx_derivers            1.2.1       Shared [@@deriving] plugin registry
ptime                   0.8.5       POSIX time for OCaml
re                      1.9.0       RE is a regular expression library for OCaml
reason                  3.6.0       Reason: Syntax & Toolchain for OCaml
result                  1.5         Compatibility Result module
seq                     base        Compatibility package for OCaml's standard iterator type st
sexplib0                v0.14.0     Library containing the definition of S-expressions and some
stdlib-shims            0.1.0       Backport some of the new stdlib features to older compiler
topkg                   1.0.2       The transitory OCaml software packager
tyxml                   4.4.0       TyXML is a library for building correct HTML and SVG docume
uchar                   0.0.2       Compatibility library for OCaml's Uchar module
uuidm                   0.9.7       Universally unique identifiers (UUIDs) for OCaml
uutf                    1.0.2       Non-blocking streaming Unicode codec for OCaml
```
Also I use vscode with [OCaml Formatter](https://marketplace.visualstudio.com/items?itemName=badochov.ocaml-formatter) and  [OCaml Platform](https://marketplace.visualstudio.com/items?itemName=ocamllabs.ocaml-platform)

And I don't often use formatter or linter for ocaml development so I'm not sure what I should use

**Comment by pbiggar** [comment]
Just to update you on this, I'm adding CI so we can establish what versions we support, and then we should be able to get this and a few other of your PRs merged.

**Comment by shubhamkumar13** [comment]
> Just to update you on this, I'm adding CI so we can establish what versions we support, and then we should be able to get this and a few other of your PRs merged.

Thanks! Sorry I didn't look into the build matrix.

**Comment by pbiggar** [comment]
This is probably good to merge - can you rebase it off main so that CI will run?

Thanks!

**Comment by pbiggar** [comment]
This was automatically closed when I deleted the master branch, apologies. We'll try to get this merged soon.

**Pull request closed without merging**
