### PR TITLE
Update types present in TableclothMap.ml's Base.Either from `Fst / `Snd to First/Second

### PR DESCRIPTION
**Pull request by shubhamkumar13**
Updated types in response to issue #175

### CODE REVIEW

**Comment by shubhamkumar13** [comment]
@pbiggar I think #176 can be merged after this is merged and I rebase with the new master

**Comment by pbiggar** [comment]
Great, thanks! Where are those types from, and what versions will this work on? I'm worried about it working for new versions and breaking for old versions.

Sorry for the hassle with these changes, really appreciate them. I'm trying to think what would provide certainty here - I think adding a build matrix to CircleCI with the different versions of Base would certainly do it - is that something you can do?

Wouldn't mind some input from @Dean177 here too.

**Comment by shubhamkumar13** [comment]
> and what versions will this work on?

I'm currently using `ocaml-base-compiler.4.10.0`

> Where are those types from

These types are from [native/src/TableclothMap.ml](https://github.com/darklang/tablecloth/blob/83480ad7b58c24fae96c246712d4082f2ff610e1/native/src/TableclothMap.ml#L99)

So as you stated in #175 `partition_mapi` from `Base.Map` uses `Base.Either` now instead of using ``[> `Fst of x | `Snd of x ]``
> I think adding a build matrix to CircleCI with the different versions of Base would certainly do it - is that something you can do?

I have not used CircleCI but I can try looking into it

**Comment by pbiggar** [comment]
I added CircleCI and a list of supported versions. I think either this isn't necessary anymore, or instead that supporting this will add extra supported versions (which would be great). Can you rebase this off main and we can see what CI says?

**Comment by pbiggar** [comment]
This is being fixed in #220. I managed to avoid using `\`Fst`/`First` and reusing an existing function instead

**Pull request closed without merging**
