### PR TITLE
Documentation  / Tests

### PR DESCRIPTION
**Pull request by jdeisenberg**
* Break long documentation lines into shorter lines
* Complete documentation for `Tablecloth.List` in `bs/src/tablecloth.mli`
* Add tests for `minimum*` and `maximum*`

### CODE REVIEW

**Comment by pbiggar** [comment]
Looks good, but CI is failing. Can you rebase the merges out as well?

**Comment by jdeisenberg** [comment]
Which branch should I rebase it against?

**Comment by pbiggar** [comment]
> Which branch should I rebase it against?

Master, but specifically I mean to remove the merge commits by rebasing it against master's HEAD.

**Comment by pbiggar** [comment]
This is what I mean: https://stackoverflow.com/questions/17577409/git-remove-merge-commit-from-history

**Comment by jdeisenberg** [comment]
I did a

   git rebase master HEAD

and resolved all the conflicts. I am now I am on this branch:

   (HEAD detached from 1096eae)

and  have no idea what to do with it.

**Comment by pbiggar** [comment]
I'm not sure either. I would `git reset --hard documentation` to go back to your branch (this will lose all changes not saved in git), and then follow the instructions in the stackoverflow link.

**Comment by jdeisenberg** [comment]
OK. I presume you want me to follow the most-voted suggestion:

Do git rebase -i <sha before the branches diverged>

I have no idea which branch is the one before they diverged, unfortunately.

**Comment by pbiggar** [comment]
You can use any commit from the PR that's before a merge, eg 8a5e18a.

**Comment by pbiggar** [comment]
Hey, how goes this? Want me to do it?

**Comment by jdeisenberg** [comment]
I was busy at the school today, so didn't have a chance to look at it again.  I tried doing the rebase yesterday, but one of the conflicts was missing part of the test for `init()`. If you could please do it, and perhaps send me an email of the shell commands you used so that I can learn how it works, that would be great.

In the future, I’ll delete the old branch after a PR is merged, create a new one with a new name, and carry on with further documentation. That should make things easier than carrying around a lot of new changes into a single branch that has already been merged.

**Comment by pbiggar** [comment]
Sure:

`git checkout documentation`
`git rebase master`

I got an error:

> First, rewinding head to replay your work on top of it...
> Applying: Further changes.
> Falling back to patching base and 3-way merge...
> Auto-merging bs/src/tablecloth.mli
> CONFLICT (content): Merge conflict in bs/src/tablecloth.mli
> error: Failed to merge in the changes.
> Resolve all conflicts manually, mark them as resolved with
> "git add/rm <conflicted_files>", then run "git rebase --continue".
> You can instead skip this commit: run "git rebase --skip".
> To abort and get back to the state before "git rebase", run "git rebase --abort".

I went to tablecloth.mli and edited the file manually to fix the merge conflict. They're marked by conflict markers (look for ===). 

After fixing it

`git add -u -- bs/src/tablecloth.mli`
`git rebase --continue`

Then it happened again and I fixed it again.

Finally, I checked it was the same as I expected:

`git diff jdeisenberg/documentation` (no output, so it's the same)

Then I pushed to your branch:

`git push -v --force-with-lease jdeisenberg documentation\:refs/heads/documentation`

**Comment by jdeisenberg** [comment]
Thanks! I have merged it into my `master` branch, and will continue with a brand new branch for the next PR.

**Pull request merged**
