### PR TITLE
Add Map.filterMap & fixed #151

### LINKED ISSUE #151: Add Map.filterMap
This should work the same way as its Array counterpart

### PR DESCRIPTION
**Pull request by pm5**

### CODE REVIEW

**Comment by pbiggar** [comment]
Thanks! Should be able to get this merged easily enough:

- needs tests in both rescript and native
- the .mli files need to match (rescript-build-and-test-9.1.4 is failing as a result)
- code needs to be formatting (use `npm run format` I think)
-

**Comment by pm5** [comment]
Hello there, fixed the formats and mli and added some tests.  Not sure what failing in build and documentations though.

**Comment by pbiggar** [comment]
> Hello there, fixed the formats and mli and added some tests. Not sure what failing in build and documentations though.

Thanks! To fix the documentation, I think you just need to run `make doc`

**Comment by pm5** [comment]
Hello there.  Finally had some time to address this :)

**Comment by pbiggar** [comment]
My apologies, I should have merged this before splitting the repos apart. We'll need to move this to the other repos

**Pull request closed without merging**
